studio/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views  # Import auth views for login/logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('producer.urls')),  # Assuming 'producer' is your project app
    path('users/', include('users.urls')),  # Include URLs for user authentication
    
]

urls.py
from django.urls import path
from .views import (
    create_project, 
    project_list, 
    delete_project, 
    project_detail, 
    edit_project,
    create_category,
    create_project_category
    )

urlpatterns = [
    path('create/', create_project, name='create_project'),
    path('', project_list, name='project_list'),
    path('<int:pk>/delete/', delete_project, name='delete_project'),
    path('<int:pk>/', project_detail, name='project_detail'),
    path('edit/<int:pk>/', edit_project, name='edit_project'),
    path('create/category', create_category, name='create_category'),
    path('create/category/project/<int:pk>/', create_project_category, name='create_project_category'),


]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Другие URL-адреса вашего приложения
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

models.py
from django.db import models

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    total_budget = models.DecimalField(decimal_places=0, max_digits=12)
    deadline = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.name

    
class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    
    def __str__(self):
        return self.name

 
class CategoryProject(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    budget = models.DecimalField(decimal_places=0, max_digits=12)
    

users/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass
    
    def __str__(self):
        return self.username

forms.py
from django import forms
from .models import Project, Category, CategoryProject

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'total_budget', 'deadline']
        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

class CategoryProjectForm(forms.ModelForm):
    class Meta:
        model = CategoryProject
        fields = ['category', 'project', 'budget']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from producer.models import Project

@login_required
def project_list(request):
    projects = Project.objects.all()  # Assuming you have a Project model
    return render(request, 'project_list.html', {'projects': projects})

def logout_view(request):
    logout(request)
    return redirect('login')  # Redirect to the login page after logout

views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProjectForm, CategoryForm, CategoryProjectForm
from .models import Project, CategoryProject
from django.contrib.auth.decorators import login_required

@login_required
def create_project(request):
    print('Erbol')
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = ProjectForm()
    return render(request, 'create_project.html', {'form': form})

@login_required
def project_list(request):
    projects = Project.objects.all().order_by('deadline')
    return render(request, 'project_list.html', {'projects': projects})

def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.delete()
    return redirect('project_list')


def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project_categories = CategoryProject.objects.filter(project_id=pk)
    return render(request, 'project_detail.html', {'project': project, 'project_categories': project_categories})

def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project_detail', pk=pk)
    else:
        form = ProjectForm(instance=project)
    return render(request, 'edit_project.html', {'form': form})

@login_required
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = CategoryForm()
    return render(request, 'create_category.html', {'form': form})


@login_required
def create_project_category(request, pk):  # Update the parameter name to project_id
    project = get_object_or_404(Project, pk=pk)  # Use project_id to get the project object

    if request.method == 'POST':
        form = CategoryProjectForm(request.POST)
        if form.is_valid():
            category_project = form.save(commit=False)
            category_project.project = project
            category_project.save()
            return redirect('project_detail', pk=pk)  # Use project_id for redirection
    else:
        form = CategoryProjectForm(initial={'project': project})

    return render(request, 'create_project_category.html', {'form': form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
</head>

<body>

    {% include "navbar.html"%}

    {% block content %}
    
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>


 
</body>
</html>

templates/create_category.html
{% extends 'base.html' %}

{% block content %}
    <div class="container ">
        <h1 class="text-center mb-4">Create Category</h1>
        <div class="card w-50 mx-auto shadow p-3 mb-5 bg-body-tertiary rounded">
            <div class="card-body ">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_name" class="form-label col-3 ">Name:</label>
                        {{ form.name }}
                    </div>
                    <div class="mb-3">
                        <label for="id_description" class="form-label col-3">Description:</label>
                        {{ form.description }}
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Create Category" class="btn btn-danger">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/create_project.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="container">
        <h1 class="text-center mb-4">Create Project</h1>
        <div class="card w-50 mx-auto shadow p-3 mb-5 bg-body-tertiary rounded">
            <div class="card-body">
                <div class="mb-3 row">
                    <label for="id_name" class="col-3 col-form-label">Name:</label>
                    <div class="col">
                        {{ form.name }}
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="id_description" class="col-3 col-form-label">Description:</label>
                    <div class="col">
                        {{ form.description }}
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="id_total_budget" class="col-3 col-form-label">Total Budget:</label>
                    <div class="col">
                        {{ form.total_budget }}
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="id_deadline" class="col-3 col-form-label">Deadline:</label>
                    <div class="col">
                        {{ form.deadline }}
                    </div>
                </div>
                <div class="text-center">
                    <input type="submit" value="Create Project" class="btn btn-danger">
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/create_project_category.html
{% extends 'base.html' %}

{% block content %}  
    <div class="container">
        <h1 class="text-center">Create Category Project</h1>
        <div class="card shadow p-3 mb-5 bg-body-tertiary rounded mx-auto" style="max-width: 400px;">
            <div class="card-body text-center">
                
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Create Category" class="btn btn-danger mt-3 d-block mx-auto">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/edit_project.html
{% extends 'base.html' %}

{% block content %}
<h1 class="card-title text-center mb-4">Edit Project</h1> 
    <div class="container">
        <div class="card shadow p-3 mb-5 bg-body-tertiary rounded mx-auto" style="max-width: 450px;">
            <div class="card-body">
                
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_name" class="form-label col-3">Name:</label>
                        {{ form.name }}
                    </div>
                    <div class="mb-3">
                        <label for="id_description" class="form-label col-3">Description:</label>
                        {{ form.description }}
                    </div>
                    <div class="mb-3">
                        <label for="id_total_budget" class="form-label col-3">Total Budget:</label>
                        {{ form.total_budget }}
                    </div>
                    <div class="mb-3">
                        <label for="id_deadline" class="form-label col-3">Deadline:</label>
                        {{ form.deadline }}
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger">Save Project</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
{% if request.user.is_authenticated %}
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-5">
    <div class="container-fluid">
        <a class="navbar-brand" href="">{{ request.user }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project_list' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_project' %}">Проект</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_category' %}">Категория</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
            <form action="{% url 'logout' %}" method="post" class="d-flex ms-2">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Logout</button>
            </form>
        </div>
    </div>
</nav>

{% endif %}

templates/project_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card shadow p-3 mb-5 bg-body-tertiary rounded mx-auto" style="max-width: 600px;">
            <div class="card-body">
                <h1>{{ project.name }}</h1>
                <p><strong>Description:</strong> {{ project.description }}</p>
                <p><strong>Total Budget:</strong> {{ project.total_budget }}</p>
                <p><strong>Deadline:</strong> {{ project.deadline }}</p>  <!-- Добавлено поле deadline -->
                
                {% for project_category in project_categories %}
                <div class="alert alert-danger" role="alert">
                    <p><strong>Category:</strong> {{ project_category.category.name }}</p>
                    <p><strong>Budget:</strong> {{ project_category.budget }}</p>
                </div>
                {% endfor %}
                
                <div class="text-center">
                    <a class="btn btn-danger" href="{% url 'edit_project' project.id %}">Edit Project</a>
                    <a class="btn btn-danger" href="{% url 'create_project_category' project.id %}">Добавить категорию расхода</a>
                    <a class="btn btn-danger" href="{% url 'project_list' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/project_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card shadow p-3 mb-5 bg-body-tertiary rounded text-center mx-auto" style="max-width: 400px;">
        <div>
            Список проектов
        </div>
        <div class="card-body" style="margin-bottom: 10px;">
            {% if user.is_authenticated %}
            {% for project in projects %}
                <a style="text-decoration:none; color: inherit;" href="{% url 'project_detail' project.id %}">
                    <span class="field-value">{{ project.name }}</span><br>
                </a>
                <a style="text-decoration:none; color: inherit;" href="{% url 'project_detail' project.id %}">
                  <span class="field-value">{{ project.deadline}}</span><br>
              </a>
            {% endfor %}
            {% else %}
                <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>, чтобы увидеть список проектов.</p>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="text-body-secondary">
                <a href="{% url 'create_project' %}" class="btn btn-danger">Добавить проект</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}